# P1.2 content, part A. One row per product:
# (sku, nameEn, nameAr, brand, specs, descriptionEn)
# Specs hold only facts stated in the current name or Arabic description.
# English descriptions translate the owner's Arabic description.

ROWS = [
("SKU-MSGCHXJL", "Best Portable Air Conditioner 10,000 BTU", "مكيف Best متنقل 10,000 وحدة", "Best",
 [("type", "Portable", "متنقل"), ("btu", 10000)],
 "Best portable air conditioner with 10,000 BTU cooling. Cools effectively and moves easily between rooms; a practical design for homes and offices."),
("SKU-MSGCRSOA", "Fresh Portable Air Conditioner 10,000 BTU", "مكيف Fresh متنقل 10,000 وحدة", "Fresh",
 [("type", "Portable", "متنقل"), ("btu", 10000)],
 "Fresh portable air conditioner with 10,000 BTU cooling. Effective cooling and easy to move, suited to homes and offices."),
("SKU-MSGCUO3E", "ICE Split Air Conditioner 6,000 BTU", "مكيف ICE ثابت 6,000 وحدة", "ICE",
 [("type", "Split (fixed)", "ثابت"), ("btu", 6000)],
 "ICE fixed air conditioner with 6,000 BTU cooling, built for effective cooling, reliable performance and economical power use."),
("SKU-MSGCT9P6", "Nasma Split Air Conditioner 6,000 BTU", "مكيف Nasma ثابت 6,000 وحدة", "Nasma",
 [("type", "Split (fixed)", "ثابت"), ("btu", 6000)],
 "Nasma fixed air conditioner with 6,000 BTU cooling. Steady cooling with efficiency suited to small rooms."),
("SKU-MSGCVT38", "ONAX Portable Air Conditioner 18,000 BTU", "مكيف ONAX متنقل 18,000 وحدة", "ONAX",
 [("type", "Portable", "متنقل"), ("btu", 18000)],
 "ONAX portable air conditioner with 18,000 BTU cooling. Strong cooling for large spaces, easy to move and operate."),
("SKU-MSGCX45F", "Sharp Split Air Conditioner 18,000 BTU", "مكيف Sharp سبليت 18,000 وحدة", "Sharp",
 [("type", "Split", "سبليت"), ("btu", 18000)],
 "Sharp split air conditioner with 18,000 BTU cooling. Strong cooling, quiet operation and high efficiency for comfort in any weather."),
("SKU-MSGCYFP3", "TCL Split Air Conditioner 18,000 BTU", "مكيف TCL سبليت 18,000 وحدة", "TCL",
 [("type", "Split", "سبليت"), ("btu", 18000)],
 "TCL split air conditioner with 18,000 BTU cooling. Fast cooling and reliable performance in a modern design for homes and offices."),
("SKU-MSGCPE27", "Unionaire Portable Air Conditioner 8,000 BTU", "مكيف Unionaire متنقل 8,000 وحدة", "Unionaire",
 [("type", "Portable", "متنقل"), ("btu", 8000)],
 "Unionaire portable air conditioner with 8,000 BTU cooling. Comfortable cooling in a design that is easy to move and operate, suited to small and medium rooms."),
("SKU-MSKM6MXK", "Air Fryer", "قلاية هوائية", None,
 [],
 "Air fryer for practical cooking with far less oil. Suitable for frying and preparing a wide range of everyday meals."),
("SKU-MSHREGNU", "LG Automatic Washing Machine 10 kg", "غسالة LG أوتوماتيك 10 كجم", "LG",
 [("type", "Automatic", "أوتوماتيك"), ("cap_kg", 10)],
 "LG automatic washing machine with a 10 kg capacity and strong washing performance, suited to large families and heavy use."),
("SKU-MSHRC497", "LG Automatic Washing Machine 7 kg", "غسالة LG أوتوماتيك 7 كجم", "LG",
 [("type", "Automatic", "أوتوماتيك"), ("cap_kg", 7)],
 "LG automatic washing machine with a 7 kg capacity. Effective washing with economical water and power use, suited to the daily needs of small families."),
("SKU-MSHRDAR9", "LG Automatic Washing Machine 8 kg", "غسالة LG أوتوماتيك 8 كجم", "LG",
 [("type", "Automatic", "أوتوماتيك"), ("cap_kg", 8)],
 "LG automatic washing machine with an 8 kg capacity. Cleans clothes efficiently with multiple wash programs and a practical design for home use."),
("SKU-MSHR1VK9", "Electric Blender", "خلاط كهربائي", None,
 [],
 "Multi-purpose electric blender for juices, smoothies and mixing ingredients. Strong motor, easy to use and to clean."),
("SKU-MSGF3H7D", "Electric Food Processor", "كبة كهربائية", None,
 [],
 "Electric food processor (kebbe) for chopping, mincing and mixing ingredients."),
("SKU-MSKM9SEI", "Hofmanns Blender", "خلاط Hofmanns", "Hofmanns",
 [],
 "Practical Hofmanns blender for juices and drinks and for mixing ingredients; suited to everyday kitchen use."),
("SKU-MSKMJZ0N", "Midea Blender", "خلاط Midea", "Midea",
 [],
 "Practical Midea blender for juices and drinks and a wide range of ingredients. Designed for everyday kitchen use and easy to operate."),
("SKU-MSKMANKO", "SilverCrest Blender", "خلاط SilverCrest", "SilverCrest",
 [],
 "SilverCrest blender for mixing and preparing a variety of ingredients and drinks, with a practical design for everyday kitchen use."),
("SKU-MSGFBFVM", "Electrical Cable", "سلك كهربائي", None,
 [],
 "Electrical wire for connections and electrical installation work."),
("SKU-MSKN9VLD", "Electric Touch Cooktop 4 Burners, Marble", "بوتاجاز كهربائي رخام باللمس 4 عيون", None,
 [("fuel", "Electric", "كهرباء"), ("burners", 4), ("surface", "Marble", "رخام"), ("controls", "Touch", "لمس")],
 "Electric touch-control cooker with a marble top and four burners. A practical, elegant and easy-to-use cooking solution for home kitchens."),
("SKU-MSHR3MCI", "Electric Hot Plate 2 Burners", "هيتر كهربائي 2 عين", None,
 [("fuel", "Electric", "كهرباء"), ("burners", 2)],
 "Two-burner electric hot plate for preparing meals at home, in offices and in small spaces. Heats quickly and is easy to use."),
("SKU-MSGELUC5", "Electric Touch Hot Plate 1 Burner", "هيتر كهربائي باللمس عين واحدة", None,
 [("fuel", "Electric", "كهرباء"), ("burners", 1), ("controls", "Touch", "لمس")],
 "Single-burner electric hot plate with a touch surface, for home use."),
("SKU-MSHQU4VI", "Star Electric Oven 100 L, Double Door", "فرن كهربائي Star بابين 100 لتر", "Star",
 [("cap_l", 100), ("doors", 2)],
 "Star double-door electric oven with a 100 L capacity, for baking, grilling and everyday cooking."),
("SKU-MSHQW4ES", "Star Electric Oven 120 L, Double Door", "فرن كهربائي Star بابين 120 لتر", "Star",
 [("cap_l", 120), ("doors", 2)],
 "Star double-door electric oven with a 120 L capacity and a large cooking space for baking, grilling and all kinds of meals. Even heat and reliable performance for home and commercial use."),
("SKU-MSHQYLOZ", "Star Electric Oven 75 L", "فرن كهربائي Star 75 لتر", "Star",
 [("cap_l", 75)],
 "Star electric oven with a 75 L capacity for baking, grilling and reheating. Easy to use, with good heat distribution for balanced results."),
("SKU-MSKLYTJQ", "Akai Electric Oven 35 L", "فرن كهربائي Akai 35 لتر", "Akai",
 [("cap_l", 35)],
 "Akai electric oven with a 35 L capacity. Reliable performance for meals and baking, easy to use and practical for home kitchens."),
("SKU-MSKM5E43", "Bestcook Electric Oven 35 L", "فرن كهربائي Bestcook 35 لتر", "Bestcook",
 [("cap_l", 35)],
 "Bestcook electric oven with a 35 L capacity, enough room for meals, baking and grilling. Practical and easy to use for everyday home cooking."),
("SKU-MSKLY3PW", "DSP Electric Oven 35 L", "فرن كهربائي DSP 35 لتر", "DSP",
 [("cap_l", 35)],
 "DSP electric oven with a 35 L capacity, built for effective cooking with good heat distribution; suited to baking, grilling and reheating."),
("SKU-MSKLXA5F", "EastPoint Electric Oven 35 L", "فرن كهربائي EastPoint 35 لتر", "EastPoint",
 [("cap_l", 35)],
 "EastPoint electric oven with a 35 L capacity. Even heat and effective cooking for all kinds of food, in a compact, easy-to-use design."),
("SKU-MSKLWAVT", "Ferre Electric Oven 35 L", "فرن كهربائي Ferre 35 لتر", "Ferre",
 [("cap_l", 35)],
 "Ferre electric oven with a 35 L capacity, combining a practical size with effective performance for everyday meals, baking and grilling."),
("SKU-MSKLVHC9", "Ferre Electric Oven 45 L", "فرن كهربائي Ferre 45 لتر", "Ferre",
 [("cap_l", 45)],
 "Ferre electric oven with a 45 L capacity for baking, grilling and reheating. Easy to operate, with even heat for excellent results."),
("SKU-MSKLUASR", "Ferre Electric Oven 60 L", "فرن كهربائي Ferre 60 لتر", "Ferre",
 [("cap_l", 60)],
 "Ferre electric oven with a 60 L capacity, room for meals, baking and grilling. Even heat and simple operation make it a good choice for the home."),
("SKU-MSHQMVTH", "Hila Hoop Fan", "مروحة هيلاهوب", None,
 [],
 "Practical fan with good airflow and steady operation for everyday use."),
("SKU-MSHPZOZJ", "KDK Fan", "مروحة KDK", "KDK",
 [],
 "High-quality KDK fan with strong airflow and reliable performance, suited to home or commercial use."),
("SKU-MSHQ3CGT", "Mayouns Stand Fan", "مروحة ستاند Mayouns باكستانية", "Mayouns",
 [("type", "Stand", "ستاند"), ("origin", "Pakistan", "باكستان")],
 "Mayouns stand fan with a practical design and strong airflow, suited to homes and offices."),
("SKU-MSGEPSYK", "Midea Stand Fan", "مروحة ستاند Midea", "Midea",
 [("type", "Stand", "ستاند")],
 "Midea floor stand fan for ventilation and air circulation."),
("SKU-MSHQKHXK", "Wall Fan", "مروحة حائط", None,
 [("type", "Wall-mounted", "حائط")],
 "Wall fan with a practical design that gives strong airflow while saving floor space; suited to homes and offices."),
("SKU-MSGA9TVM", "BestCool Chest Freezer 12 cu ft", "فريزر BestCool أفقي 12 قدم", "BestCool",
 [("type", "Chest", "أفقي"), ("cap_cuft", 12)],
 "BestCool chest freezer with a 12 cu ft capacity. Large storage, fast freezing and reliable performance for keeping frozen food for long periods."),
("SKU-MSGAI8QB", "BestCool Hafab Chest Freezer 19 cu ft", "فريزر BestCool Hafab أفقي 19 قدم", "BestCool",
 [("type", "Chest", "أفقي"), ("cap_cuft", 19), ("model", "Hafab", "Hafab")],
 "BestCool Hafab chest freezer with a 19 cu ft capacity and strong freezing, suited to home and commercial use."),
("SKU-MSGAKDD1", "BestCool Hafab Display Freezer, 2 Doors", "فريزر BestCool Hafab عرض بابين", "BestCool",
 [("type", "Display", "عرض"), ("doors", 2), ("model", "Hafab", "Hafab")],
 "BestCool Hafab two-door display freezer. Fast cooling with economical power use; a good choice for homes and small shops."),
("SKU-MSGASCKH", "BestCool Haftec Display Freezer 8 cu ft", "فريزر BestCool Haftec عرض 8 قدم", "BestCool",
 [("type", "Display", "عرض"), ("cap_cuft", 8), ("model", "Haftec", "Haftec")],
 "BestCool freezer with an 8 cu ft capacity, built for steady freezing and practical storage in a sturdy, easy-to-use design."),
("SKU-MSGB4MLW", "Haftec Chest Freezer 8 cu ft", "فريزر Haftec أفقي 8 قدم", "Haftec",
 [("type", "Chest", "أفقي"), ("cap_cuft", 8)],
 "Haftec freezer with an 8 cu ft capacity. Effective freezing and suitable storage for frozen food, with efficient power use."),
("SKU-MSC29SO7", "LG Upright Freezer 10 cu ft", "فريزر LG رأسي 10 قدم", "LG",
 [("type", "Upright", "رأسي"), ("cap_cuft", 10)],
 "LG upright freezer with plenty of storage and practical shelves and drawers to keep frozen food organised. Strong freezing in an elegant design for homes and shops."),
("SKU-MSGB3G24", "M.T Chest Freezer 8 cu ft", "فريزر M.T أفقي 8 قدم", "M.T",
 [("type", "Chest", "أفقي"), ("cap_cuft", 8)],
 "M.T chest freezer with an 8 cu ft capacity. Fast freezing, practical storage, economical power use and a sturdy design for home and commercial use."),
("SKU-MSGA6WFM", "Midea Chest Freezer 12 cu ft", "فريزر Midea أفقي 12 قدم", "Midea",
 [("type", "Chest", "أفقي"), ("cap_cuft", 12)],
 "Midea chest freezer with fast freezing, suitable storage and economical power use, for home or commercial use."),
("SKU-MSGB6I91", "Nikai Chest Freezer 6 cu ft", "فريزر Nikai أفقي 6 قدم", "Nikai",
 [("type", "Chest", "أفقي"), ("cap_cuft", 6)],
 "Compact Nikai freezer with a 6 cu ft capacity. Fast freezing and reliable performance for homes and small shops."),
("SKU-MSG9UB88", "StarTech Chest Freezer 8 cu ft", "فريزر StarTech أفقي 8 قدم", "StarTech",
 [("type", "Chest", "أفقي"), ("cap_cuft", 8)],
 "StarTech chest freezer with an 8 cu ft capacity. Fast freezing and suitable storage for meat and frozen food over long periods, with economical power use."),
("SKU-MSG9VB9Q", "StarTech Chest Freezer", "فريزر StarTech أفقي", "StarTech",
 [("type", "Chest", "أفقي")],
 "StarTech chest freezer with large storage and strong cooling, suited to homes, shops and restaurants."),
("SKU-MSG9W5VQ", "StarTech M.T Chest Freezer 14 cu ft", "فريزر StarTech M.T أفقي 14 قدم", "StarTech",
 [("type", "Chest", "أفقي"), ("cap_cuft", 14), ("model", "M.T", "M.T")],
 "StarTech M.T freezer with a 14 cu ft capacity. Large storage and fast freezing to keep food quality, with a sturdy design and economical power use."),
("UNI-CFREEZER-282", "Unionaire Chest Freezer 12 cu ft", "فريزر Unionaire أفقي 12 قدم", "Unionaire",
 [("type", "Chest", "أفقي"), ("cap_cuft", 12)],
 "Unionaire chest freezer with reliable freezing and a roomy interior for all kinds of frozen food. Easy to use and well built for home and commercial use."),
("UNI-CFREEZER-250", "Unionaire Chest Freezer 9 cu ft", "فريزر Unionaire أفقي 9 قدم", "Unionaire",
 [("type", "Chest", "أفقي"), ("cap_cuft", 9)],
 "Unionaire chest freezer with large storage for keeping big amounts of frozen food for long periods. Its practical design suits homes, restaurants and shops, with efficient freezing."),
("UNI-UPFREEZER-230", "Unionaire Upright Freezer, 6 Drawers", "فريزر Unionaire رأسي 6 أدراج", "Unionaire",
 [("type", "Upright", "رأسي"), ("drawers", 6)],
 "Unionaire upright freezer with organised storage and easy access thanks to its vertical design. Keeps all kinds of frozen food with steady cooling; practical for homes and shops."),
("SKU-MSGDJGYG", "Newdale Gas Burner 3 Burners", "شعلة Newdale 3 عيون", "Newdale",
 [("fuel", "Gas", "غاز"), ("burners", 3)],
 "Newdale three-burner gas stove with even heat and reliable performance for everyday cooking."),
("SKU-MSGDL5P4", "Nikai Gas Burner 3 Burners", "شعلة Nikai 3 عيون", "Nikai",
 [("fuel", "Gas", "غاز"), ("burners", 3)],
 "Nikai three-burner gas stove, well built with steady performance, suited to home use."),
("SKU-MSGFNLTJ", "Nikura Burner", "شعلة Nikura", "Nikura",
 [("fuel", "Gas / electric", "غاز / كهرباء")],
 "Nikura gas/electric burner for cooking."),
("SKU-MSHQZJE3", "Gas Cooker 4 Burners, Marble", "بوتاجاز رخام 4 عيون", None,
 [("fuel", "Gas", "غاز"), ("burners", 4), ("surface", "Marble", "رخام")],
 "Gas cooker with a marble top and four burners. Even heat and a practical, easy-to-clean design for everyday home cooking."),
("SKU-MSKN2QPM", "Bestcook Gas Cooker 5 Burners", "بوتاجاز Bestcook 5 عيون", "Bestcook",
 [("fuel", "Gas", "غاز"), ("burners", 5)],
 "Bestcook gas cooker with five burners, room to cook several dishes at once, in a practical design for everyday home use."),
("SKU-MSKMP11C", "Digi Gas Cooker 5 Burners", "بوتاجاز Digi 5 عيون", "Digi",
 [("fuel", "Gas", "غاز"), ("burners", 5)],
 "Digi cooker with five burners, room to cook several dishes at once, in a practical design for everyday home use."),
("SKU-MSKMPS33", "Digi Cooker 6 Burners (4 Gas + 2 Electric)", "بوتاجاز Digi 6 عيون (4 غاز + 2 كهرباء)", "Digi",
 [("fuel", "4 gas + 2 electric", "4 غاز + 2 كهرباء"), ("burners", 6)],
 "Digi cooker with six burners: four gas and two electric. Plenty of room to cook several dishes at once, in a practical design for home kitchens."),
("SKU-MSKN5C9V", "Fresh Gas Cooker 4 Burners", "بوتاجاز Fresh 4 عيون", "Fresh",
 [("fuel", "Gas", "غاز"), ("burners", 4)],
 "Fresh gas cooker with four burners: a practical everyday cooker, sized for home kitchens and easy to use."),
("SKU-MSKN4417", "Fresh Gas Cooker 5 Burners", "بوتاجاز Fresh 5 عيون", "Fresh",
 [("fuel", "Gas", "غاز"), ("burners", 5)],
 "Fresh gas cooker with five burners for everyday cooking, with practical room for several meals and an easy-to-use design."),
("SKU-MSKMQH3B", "Glem Gas Cooker 5 Burners", "بوتاجاز Glem إيطالي 5 عيون", "Glem",
 [("fuel", "Gas", "غاز"), ("burners", 5), ("origin", "Italy", "إيطاليا")],
 "Italian Glem cooker with five burners, practical room to cook several dishes at once, designed for everyday kitchen use."),
("SKU-MSKN8NLD", "Hafab Gas Cooker 4 Burners, Marble", "بوتاجاز Hafab رخام 4 عيون", "Hafab",
 [("fuel", "Gas", "غاز"), ("burners", 4), ("surface", "Marble", "رخام")],
 "Hafab gas cooker with a marble top and four burners for everyday cooking, in a practical design for home use."),
("SKU-MSHQ5QJH", "Hafab Gas Cooker 4 Burners, Marble, with Hood", "بوتاجاز Hafab رخام مع شفاط 4 عيون", "Hafab",
 [("fuel", "Gas", "غاز"), ("burners", 4), ("surface", "Marble", "رخام"), ("feature", "Built-in hood", "شفاط مدمج")],
 "Hafab gas cooker with a marble top, a built-in hood and four burners, combining a practical design with reliable everyday performance."),
("SKU-MSKN6JOW", "Haftec Gas Cooker 4 Burners, Marble", "بوتاجاز Haftec رخام 4 عيون", "Haftec",
 [("fuel", "Gas", "غاز"), ("burners", 4), ("surface", "Marble", "رخام")],
 "Haftec gas cooker with a marble top and four burners, practical and easy to clean, suited to everyday kitchen use."),
("SKU-MSKN7NMD", "Haftec Gas Cooker 5 Burners, Marble", "بوتاجاز Haftec رخام 5 عيون", "Haftec",
 [("fuel", "Gas", "غاز"), ("burners", 5), ("surface", "Marble", "رخام")],
 "Haftec gas cooker with a marble top and five burners: plenty of room to cook several dishes at once, practical and easy to clean."),
("SKU-MSGERZYT", "Electric Ice Crusher 500 W", "كسارة ثلج كهربائية 500 واط", None,
 [("watt", 500)],
 "Electric ice crusher for making crushed ice, 500 W."),
("SKU-MSGFIION", "Power Inverter", "انفيرتر", None,
 [],
 "Device that converts DC power to AC power."),
("SKU-MSGFMZ5F", "UPS 1500 VA", "جهاز UPS (بطارية شحن) 1500 VA", None,
 [("type", "UPS", "UPS"), ("va", 1500)],
 "Rechargeable UPS backup power unit rated 1500 VA."),
("SKU-MSGFLXAQ", "UPS 850 VA", "جهاز UPS (بطارية شحن) 850 VA", None,
 [("type", "UPS", "UPS"), ("va", 850)],
 "Rechargeable UPS backup power unit rated 850 VA."),
("SKU-MSHR7EGP", "Electric Dry Iron", "مكواة كهربائية", None,
 [("type", "Dry", "جافة")],
 "Electric iron for fast, effective ironing with even heat, suited to all kinds of fabric."),
]
