# P1.2 content, part B. Same shape as part A; an optional 7th item replaces the
# Arabic description (used only where the old one was misleading).

ROWS = [
("SKU-MSHR9UWX", "Nikai Steam Iron", "مكواة بخار Nikai", "Nikai",
 [("type", "Steam", "بخار")],
 "Nikai steam iron for fast, effective ironing, with even steam and heat that remove creases easily from all kinds of fabric. Easy to use and reliable every day."),
("SKU-MSHRAWPP", "Sayonapps Steam Iron", "مكواة بخار Sayonapps", "Sayonapps",
 [("type", "Steam", "بخار")],
 "Sayonapps steam iron with practical performance and good steam distribution, for easy ironing and excellent results in a short time."),
("SKU-MSGFKT6O", "Marado Coffee Pot", "كنكة قهوة Marado", "Marado",
 [],
 "Marado coffee pot for making coffee."),
("SKU-MSKMLVSH", "Midea Electric Kettle", "كاتيل كهربائي Midea", "Midea",
 [],
 "Midea electric kettle for boiling water quickly and easily; for tea, coffee and other hot drinks at home or in the office."),
("SKU-MSKML3RX", "Midea Glass Electric Kettle", "كاتيل كهربائي زجاج Midea", "Midea",
 [("material", "Glass", "زجاج")],
 "Midea glass electric kettle for boiling and heating water quickly and easily, with a practical, elegant design for daily use at home or in the office."),
("SKU-MSGEQXSZ", "Street Light", "إضاءة شارع", None,
 [("use", "Outdoor", "خارجي")],
 "Outdoor floodlight / lamp for streets and open areas."),
("SKU-MSKM7BMM", "LG Microwave Oven 20 L", "مايكرويف LG 20 لتر", "LG",
 [("cap_l", 20)],
 "LG microwave with a 20 L capacity for heating and cooking a variety of food; a practical size for home kitchens and small spaces."),
("SKU-MSKM9257", "LG Microwave Oven 42 L", "مايكرويف LG 42 لتر", "LG",
 [("cap_l", 42)],
 "LG microwave with a 42 L capacity, a larger interior for heating and preparing bigger amounts of food; suited to everyday home use."),
("SKU-MSKM8L7R", "Midea Microwave Oven 20 L", "مايكرويف Midea 20 لتر", "Midea",
 [("cap_l", 20)],
 "Midea microwave with a 20 L capacity, a practical way to heat and prepare food, sized for everyday home use."),
("SKU-MSGFAE4R", "DSP Electric Grater", "مفراكة كهربائية DSP", "DSP",
 [],
 "DSP electric grater (mafraka) for preparing and chopping food."),
("SKU-MSKMNZEL", "DSP Meat Grinder", "مفرمة لحم DSP", "DSP",
 [],
 "DSP electric meat grinder for mincing meat and other ingredients easily; practical food preparation at home."),
("SKU-MSGETE5W", "SilverCrest Grinder 200 g", "سحان SilverCrest كبير 200 جرام", "SilverCrest",
 [("cap_g", 200)],
 "SilverCrest grinder with a 200 g capacity."),
("SKU-MSHR8HQP", "Electric Stand Mixer", "عجانة كهربائية", None,
 [],
 "Multi-purpose electric stand mixer for kneading dough, whisking eggs and mixing ingredients, with strong performance that makes kitchen work easier."),
("SKU-MSHQRBSE", "Pressure Cooker 16 L", "حلة ضغط 16 لتر", None,
 [("cap_l", 16)],
 "Pressure cooker with a 16 L capacity for fast cooking while keeping food quality."),
("SKU-MSGFA40G", "Disney Electric Pressure Cooker", "حلة ضغط كهربائية Disney", "Disney",
 [("type", "Electric", "كهربائية")],
 "Smart electric pressure cooker for home use."),
("SKU-MSKMN1QM", "Midea Pressure Cooker", "حلة ضغط Midea", "Midea",
 [],
 "Midea pressure cooker that makes cooking easier and faster, preparing a variety of food efficiently while keeping its flavour."),
("SKU-MSGFCTVO", "Dansat Satellite Receiver", "رسيفر Dansat", "Dansat",
 [],
 "Dansat satellite TV receiver."),
("SKU-MSGFEX62", "LNB Satellite Dish Signal Receiver", "LNB لاقط إشارة دش", None,
 [],
 "Signal receiver mounted on the satellite dish; it picks up the satellite signal and passes it to the receiver."),
("SKU-MSG9ZTJH", "BestCool Double-Door Refrigerator 10 cu ft (Freezing)", "ثلاجة BestCool بابين 10 قدم (تجميد)", "BestCool",
 [("doors", 2), ("cap_cuft", 10), ("variant", "Freezing", "تجميد")],
 "BestCool refrigerator with a 10 cu ft capacity, top freezer and effective cooling. Reliable with economical power use; suited to everyday home use."),
("SKU-MSGA0LDV", "BestCool Refrigerator 12 cu ft (Freezing)", "ثلاجة BestCool 12 قدم (تجميد)", "BestCool",
 [("cap_cuft", 12), ("variant", "Freezing", "تجميد")],
 "BestCool refrigerator with a modern design and high-efficiency cooling, practical storage that keeps food and drinks fresh."),
("SKU-MSGA28OH", "BestCool Refrigerator 12 cu ft (Steam)", "ثلاجة BestCool 12 قدم (بخارية)", "BestCool",
 [("cap_cuft", 12), ("variant", "Steam (bukhariya)", "بخارية")],
 "BestCool refrigerator built for steady cooling and storage suited to daily use, with economical operation and an elegant design."),
("SKU-MSGB6VNT", "Candis Double-Door Refrigerator 12 cu ft", "ثلاجة Candis بابين 12 قدم", "Candis",
 [("doors", 2), ("cap_cuft", 12)],
 "Candis refrigerator with a 12 cu ft capacity, top freezer and effective cooling. Spacious storage that keeps food fresh for longer."),
("SKU-MSGC4UVE", "Hafab Upright Refrigerator", "ثلاجة Hafab استاند", "Hafab",
 [("type", "Upright", "استاند")],
 "Hafab upright refrigerator with spacious storage and effective cooling, suited to home and commercial use."),
("SKU-MSC204QU", "LG Double-Door Refrigerator 10 cu ft", "ثلاجة LG بابين 10 قدم", "LG",
 [("doors", 2), ("cap_cuft", 10)],
 "LG double-door refrigerator with a 10 cu ft capacity, built for effective cooling and ideal food storage in an elegant design for any kitchen. High build quality, practical storage and economical power use make it a good choice for everyday home use."),
("SKU-MSC25XWT", "LG Double-Door Refrigerator 12 cu ft", "ثلاجة LG بابين 12 قدم", "LG",
 [("doors", 2), ("cap_cuft", 12)],
 "LG double-door refrigerator with a 12 cu ft capacity. Strong cooling with balanced airflow keeps food fresh for longer; a modern design, spacious storage and efficient power use for everyday use."),
("SKU-MSC27BDL", "LG Double-Door Refrigerator 14 cu ft", "ثلاجة LG بابين 14 قدم", "LG",
 [("doors", 2), ("cap_cuft", 14)],
 "LG double-door refrigerator with a 14 cu ft capacity, combining large storage with an elegant design. Fast, effective cooling keeps food and drinks at their best, with practical, easy-to-organise shelves."),
("SKU-MSC28KET", "LG Double-Door Refrigerator 16 cu ft", "ثلاجة LG بابين 16 قدم", "LG",
 [("doors", 2), ("cap_cuft", 16)],
 "LG double-door refrigerator with a 16 cu ft capacity. Large storage and advanced cooling keep food fresh, in a modern design with economical power use."),
("SKU-MSC2AZ8E", "LG Double-Door Refrigerator 20 cu ft", "ثلاجة LG بابين 20 قدم", "LG",
 [("doors", 2), ("cap_cuft", 20)],
 "LG double-door refrigerator with a 20 cu ft capacity. Large storage and advanced cooling keep food fresh for longer, in a premium design for modern kitchens."),
("SKU-MSC2BZZZ", "LG Double-Door Refrigerator 23 cu ft", "ثلاجة LG بابين 23 قدم", "LG",
 [("doors", 2), ("cap_cuft", 23)],
 "LG double-door refrigerator with a 23 cu ft capacity, designed for large families. Spacious storage and effective cooling keep food fresh, with an elegant design and high build quality."),
("SKU-MSC2F16Q", "LG Inverter Refrigerator", "ثلاجة LG إنفرتر", "LG",
 [("feature", "Inverter compressor", "إنفرتر")],
 "LG refrigerator with inverter technology: steady cooling with lower power use and quieter operation, keeping food fresh while cutting electricity use."),
("SKU-MSC23COG", "LG Single-Door Refrigerator 10 cu ft", "ثلاجة LG باب واحد 10 قدم", "LG",
 [("doors", 1), ("cap_cuft", 10)],
 "LG single-door refrigerator with a 10 cu ft capacity. Steady cooling in a practical design for small and medium spaces; high quality, easy to use, low power use and storage that fits daily needs."),
("SKU-MSC2E34Q", "LG Smart Refrigerator", "ثلاجة LG سمارت", "LG",
 [("feature", "Smart", "سمارت")],
 "LG Smart refrigerator with smart features that improve cooling efficiency and ease of use, in a modern design for today's kitchens."),
("SKU-MSGB7MOU", "StarTech Double-Door Refrigerator 10 cu ft", "ثلاجة StarTech بابين 10 قدم", "StarTech",
 [("doors", 2), ("cap_cuft", 10)],
 "StarTech refrigerator with a 10 cu ft capacity, elegant design and high-efficiency cooling. Reliable with economical power use; suited to everyday use."),
("SKU-MSG9OBGU", "StarTech Double-Door Refrigerator 12 cu ft", "ثلاجة StarTech بابين 12 قدم", "StarTech",
 [("doors", 2), ("cap_cuft", 12)],
 "StarTech refrigerator with a 12 cu ft capacity. Steady cooling and more storage for a family's daily needs, with a top freezer, practical shelves and an elegant design."),
("SKU-MSG9PIH1", "StarTech Double-Door Refrigerator 14 cu ft", "ثلاجة StarTech بابين 14 قدم", "StarTech",
 [("doors", 2), ("cap_cuft", 14)],
 "StarTech refrigerator with a 14 cu ft capacity. Large storage and effective cooling keep food fresh for longer, with a top freezer and several shelves for easy organising."),
("UNI-REF-10FT-320", "Unionaire Refrigerator 10 cu ft", "ثلاجة Unionaire 10 قدم", "Unionaire",
 [("cap_cuft", 10)],
 "Unionaire refrigerator with a 10 cu ft capacity. Reliable cooling and practical storage for daily use at home or in the office; an elegant design with shelves that make organising easy, and steady, efficient cooling."),
("UNI-REF-12FT-440", "Unionaire Double-Door Refrigerator 12 cu ft (Frost / No Frost)", "ثلاجة Unionaire بابين 12 قدم (فروست / نوفروست)", "Unionaire",
 [("doors", 2), ("cap_cuft", 12), ("variant", "Frost or No Frost, by model", "فروست أو نوفروست حسب الموديل")],
 "Unionaire 12 cu ft refrigerator with storage suited to families and effective cooling that keeps food and drinks fresh. Available as Frost or No Frost depending on the model, with good cold distribution, practical shelves and a design for any kitchen."),
("UNI-REF-14FT-600", "Unionaire Double-Door Refrigerator 14 cu ft", "ثلاجة Unionaire بابين 14 قدم", "Unionaire",
 [("doors", 2), ("cap_cuft", 14), ("model", "Disri", "Disri")],
 "Unionaire 14 cu ft refrigerator with large storage for home use and effective cooling that keeps food and drinks at their best. A practical interior makes organising easy, and the modern look adds elegance to the kitchen."),
("UNI-REF-16FT-600", "Unionaire Double-Door Refrigerator 16 cu ft", "ثلاجة Unionaire بابين 16 قدم", "Unionaire",
 [("doors", 2), ("cap_cuft", 16)],
 "Unionaire 16 cu ft refrigerator with spacious storage for large families, steady cooling and an interior that makes arranging all kinds of food easy. Practical and elegant for everyday use."),
("UNI-REF-18FT-700", "Unionaire Double-Door Refrigerator 18 cu ft", "ثلاجة Unionaire بابين 18 قدم", "Unionaire",
 [("doors", 2), ("cap_cuft", 18)],
 "Unionaire 18 cu ft refrigerator built for large storage with high cooling efficiency, for homes that need extra room for food and drinks. Easy to use and reliably built."),
("UNI-REF-20FT-800", "Unionaire Double-Door Refrigerator 20 cu ft", "ثلاجة Unionaire بابين 20 قدم", "Unionaire",
 [("doors", 2), ("cap_cuft", 20)],
 "The Unionaire 20 cu ft refrigerator is ideal for large families, with spacious storage and effective cooling for food and drinks. A practical design and solid build make it reliable every day."),
("SKU-MSGC91OP", "Nikai Refrigerator 6 cu ft (Used)", "ثلاجة Nikai مستعملة 6 قدم", "Nikai",
 [("cap_cuft", 6), ("condition", "Used, in good working order", "مستعملة بحالة تشغيل جيدة")],
 "Used Nikai refrigerator in good working order, suited to commercial use or workplaces, with effective cooling for daily use."),
("SKU-MSGEU5E3", "Digital Price Scale 40 kg", "ميزان رقمي حاسب للسعر 40 كجم", None,
 [("max_kg", 40), ("display", "Weight, unit price, total price", "الوزن، سعر الوحدة، السعر الإجمالي")],
 "Digital price-computing scale, up to 40 kg, with displays for weight, unit price and total price.",
 "ميزان رقمي حاسب للسعر يتحمل حتى 40 كيلوجرام، يعرض الوزن وسعر الوحدة والسعر الإجمالي."),
("SKU-MSGFGV5J", "Movable TV Stand", "حامل شاشة متحرك", None,
 [],
 "Movable stand for mounting and holding TV screens."),
("SKU-MSGDRAZ3", "Dansat LED TV 43 in", "شاشة Dansat 43 بوصة", "Dansat",
 [("screen", 43)],
 "Dansat 43-inch TV with high picture quality and a modern design for homes and offices."),
("SKU-MSGDWVZC", "LG LED TV 49 in", "شاشة LG 49 بوصة", "LG",
 [("screen", 49)],
 "LG 49-inch TV with excellent picture quality, vivid colours and an elegant design."),
("SKU-MSGDVLHX", "SKY LED TV 32 in", "شاشة SKY 32 بوصة", "SKY",
 [("screen", 32)],
 "SKY 32-inch TV with a clear picture and a practical design for everyday use."),
("SKU-MSHQ108K", "Samsung LED TV 43 in", "شاشة Samsung 43 بوصة", "Samsung",
 [("screen", 43)],
 "Samsung 43-inch TV with high picture quality and clear colours, in an elegant design for many uses."),
("SKU-MSHQ24EQ", "Samsung LED TV 55 in", "شاشة Samsung 55 بوصة", "Samsung",
 [("screen", 55)],
 "Samsung 55-inch TV for a great viewing experience, with a clear picture and modern design."),
("SKU-MSHRJW1Y", "Azim Twin-Tub Washing Machine 10 kg", "غسالة Azim حوضين 10 كجم", "Azim",
 [("type", "Twin-tub", "حوضين"), ("cap_kg", 10)],
 "Azim twin-tub washing machine with a 10 kg capacity, built for fast, effective washing with reliable performance and easy use every day."),
("SKU-MSHRKS1R", "Digi Twin-Tub Washing Machine 10 kg", "غسالة Digi حوضين 10 كجم", "Digi",
 [("type", "Twin-tub", "حوضين"), ("cap_kg", 10)],
 "Digi twin-tub washing machine with a 10 kg capacity. Reliable washing and spinning in a practical design sized for daily needs."),
("SKU-MSHRG6Y9", "Fresh Twin-Tub Washing Machine 10 kg", "غسالة Fresh حوضين 10 كجم", "Fresh",
 [("type", "Twin-tub", "حوضين"), ("cap_kg", 10)],
 "Fresh twin-tub washing machine with a 10 kg capacity. Effective washing and a family-sized capacity, easy to operate and maintain."),
("SKU-MSHRI5KM", "Fresh Twin-Tub Washing Machine 8 kg", "غسالة Fresh حوضين 8 كجم", "Fresh",
 [("type", "Twin-tub", "حوضين"), ("cap_kg", 8)],
 "Fresh twin-tub washing machine with an 8 kg capacity. Reliable, sized for small and medium families, simple to operate and efficient with water and power."),
("SKU-MSHRHETZ", "Fresh Twin-Tub Washing Machine 9 kg", "غسالة Fresh حوضين 9 كجم", "Fresh",
 [("type", "Twin-tub", "حوضين"), ("cap_kg", 9)],
 "Fresh twin-tub washing machine with a 9 kg capacity. Effective washing and fast spinning in a practical, easy-to-use design for a family's daily needs."),
("SKU-MSHRIZEN", "Hafab Twin-Tub Washing Machine 10 kg", "غسالة Hafab حوضين 10 كجم", "Hafab",
 [("type", "Twin-tub", "حوضين"), ("cap_kg", 10)],
 "Hafab twin-tub washing machine with a 10 kg capacity. Effective washing and spinning with a large capacity for home use; easy to operate and durable."),
("SKU-MSHRFBMA", "LG Twin-Tub Washing Machine 10 kg", "غسالة LG حوضين 10 كجم", "LG",
 [("type", "Twin-tub", "حوضين"), ("cap_kg", 10)],
 "LG twin-tub washing machine with a 10 kg capacity. Easy to use with fast washing and spinning, in a practical design for daily use."),
("SKU-MSGEIKP8", "Aknan Voltage Regulator 500 VA", "منظم كهرباء Aknan 500 VA", "Aknan",
 [("va", 500)],
 "Aknan voltage regulator that stabilises power and protects appliances from current fluctuations; 500 VA."),
("SKU-MSGE0N51", "Marshall Voltage Regulator 3000 VA", "منظم كهرباء Marshall 3000 VA", "Marshall",
 [("va", 3000)],
 "Marshall voltage regulator rated 3000 VA, protecting appliances from high and low voltage and stabilising the power supply."),
("SKU-MSGEK8C3", "Primax Voltage Regulator 1000 VA", "منظم كهرباء Primax 1000 VA", "Primax",
 [("va", 1000)],
 "Primax voltage regulator that stabilises voltage and protects appliances; 1000 VA."),
("SKU-MSHR6GF8", "Voltage Stabilizer", "منظم كهرباء", None,
 [],
 "Voltage stabilizer that protects electrical appliances from voltage fluctuations, helping them perform better and last longer."),
("SKU-MSGF6P5C", "Jabr Voltage Regulator 2000 VA", "منظم كهرباء Jabr مائي 2000 VA", "Jabr",
 [("va", 2000)],
 "Jabr voltage regulator that stabilises the current and protects appliances from voltage fluctuations; 2000 VA."),
("SKU-MSGENVHU", "Geepas Water Cooler", "مبرد مياه Geepas", "Geepas",
 [],
 "Geepas water cooler providing cold water for home and office use."),
("SKU-MSGEOT0O", "Grand Water Cooler", "مبرد مياه Grand", "Grand",
 [],
 "Grand water cooler for chilling water."),
("SKU-MSGEMNQB", "Prime Water Cooler", "مبرد مياه Prime", "Prime",
 [],
 "Prime water cooler for chilling and dispensing water at home or in the office."),
("SKU-MSHQOS0T", "Water Cooler", "مبرد مياه", None,
 [],
 "Water cooler with excellent cooling and economical power use, suited to homes and offices."),
("SKU-MSGFJO2V", "Water Pump Motor", "موتور مياه", None,
 [],
 "Motor for pumping water, for home or commercial use."),
]

# Same product listed twice; this copy has no photo (user decision 2026-10-05).
REMOVE = ["SKU-MSG9LBZN"]
