// Development catalog. Placeholder taxonomy until P1.1 designs the real one
// from the store's actual products. Prices in SDG.

const IMG = (id) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=1200&q=80`;

export const PARENT_CATEGORIES = [
  { name: "Lighting", nameAr: "الإنارة", description: "LED bulbs, panels and floodlights", image: IMG("photo-1517999349371-c43520457b23") },
  { name: "Cables & Wires", nameAr: "الكابلات والأسلاك", description: "Power, network and coaxial cables", image: IMG("photo-1544724569-5f546fd6f2b5") },
  { name: "Switches & Sockets", nameAr: "المفاتيح والمقابس", description: "Wall switches, sockets and extension leads", image: IMG("photo-1621905251918-48416bd8575a") },
  { name: "Distribution & Protection", nameAr: "التوزيع والحماية", description: "Breakers, RCDs and distribution boards", image: IMG("photo-1581092921461-39b9d08a9b2b") },
  { name: "Power Systems", nameAr: "أنظمة الطاقة", description: "Solar, inverters and UPS", image: IMG("photo-1509391366360-2e959784a276") },
  { name: "Tools & Testers", nameAr: "العدد وأجهزة القياس", description: "Meters, testers and electrician hand tools", image: IMG("photo-1558618666-fcd25c85cd64") },
];

export const SUB_CATEGORIES = [
  { name: "LED Bulbs", nameAr: "لمبات LED", parent: "Lighting" },
  { name: "Panels & Floodlights", nameAr: "بانلات وكشافات", parent: "Lighting" },
  { name: "Power Cables", nameAr: "كابلات الكهرباء", parent: "Cables & Wires" },
  { name: "Network & Coaxial Cables", nameAr: "كابلات الشبكات والكواكسيال", parent: "Cables & Wires" },
  { name: "Wall Switches", nameAr: "مفاتيح الحائط", parent: "Switches & Sockets" },
  { name: "Sockets & Extensions", nameAr: "المقابس والتوصيلات", parent: "Switches & Sockets" },
  { name: "Circuit Breakers", nameAr: "القواطع", parent: "Distribution & Protection" },
  { name: "Distribution Boards", nameAr: "لوحات التوزيع", parent: "Distribution & Protection" },
  { name: "Solar Energy", nameAr: "الطاقة الشمسية", parent: "Power Systems" },
  { name: "Inverters & UPS", nameAr: "الانفرترات وأجهزة UPS", parent: "Power Systems" },
  { name: "Meters & Testers", nameAr: "أجهزة القياس والفحص", parent: "Tools & Testers" },
  { name: "Hand Tools", nameAr: "العدد اليدوية", parent: "Tools & Testers" },
];

const P = (sku, category, nameEn, nameAr, descriptionEn, descriptionAr, unit, purchasePrice, sellingPrice, stock, minStock, origin, countryOfOrigin, specs) => ({
  sku, category, nameEn, nameAr, descriptionEn, descriptionAr, unit, purchasePrice, sellingPrice, stock, minStock, origin, countryOfOrigin, specs,
});

export const PRODUCTS = [
  P("LED-BLB-12W", "LED Bulbs", "LED Bulb 12W E27 Daylight", "لمبة LED ‏12 واط E27 ضوء نهاري",
    "Energy-saving 12W LED bulb with a standard E27 base and bright 6500K daylight output.",
    "لمبة LED موفرة للطاقة بقدرة 12 واط وقاعدة E27 القياسية، بإضاءة نهارية ساطعة 6500 كلفن.",
    "pcs", 2200, 3500, 300, 40, "IMPORTED", "China", { Power: "12 W", Base: "E27", "Color temperature": "6500 K", Lifetime: "15,000 h" }),
  P("LED-BLB-SMART9", "LED Bulbs", "Smart LED Bulb 9W RGB Wi-Fi", "لمبة LED ذكية ‏9 واط RGB واي فاي",
    "Wi-Fi smart bulb with 16 million colours, dimming and schedules from a phone app.",
    "لمبة ذكية تعمل بالواي فاي بـ16 مليون لون، مع تعتيم وجدولة من تطبيق الهاتف.",
    "pcs", 4800, 7500, 80, 10, "IMPORTED", "China", { Power: "9 W", Base: "E27", Control: "Wi-Fi app" }),
  P("LED-PNL-6060", "Panels & Floodlights", "LED Panel 60×60 cm 48W", "بانل LED ‏60×60 سم 48 واط",
    "Slim recessed LED panel for false ceilings, 48W with even, glare-free light.",
    "بانل LED نحيف للأسقف المستعارة بقدرة 48 واط وإضاءة متجانسة بدون زغللة.",
    "pcs", 9000, 14500, 60, 10, "IMPORTED", "China", { Power: "48 W", Size: "60 × 60 cm", "Color temperature": "4000 K" }),
  P("LED-FLD-100W", "Panels & Floodlights", "LED Floodlight 100W IP65", "كشاف LED ‏100 واط IP65",
    "Outdoor 100W floodlight with an IP65 weatherproof aluminium body for yards and facades.",
    "كشاف خارجي 100 واط بهيكل ألمنيوم مقاوم للماء والغبار IP65 للأحواش والواجهات.",
    "pcs", 14000, 22000, 25, 5, "IMPORTED", "China", { Power: "100 W", Protection: "IP65", Lumens: "9,000 lm" }),
  P("CBL-CU-2.5-100", "Power Cables", "Copper Wire 2.5 mm² — 100 m Roll", "سلك نحاس 2.5 مم² — لفة 100 م",
    "Single-core PVC-insulated copper wire for sockets and general house wiring.",
    "سلك نحاس أحادي القلب معزول PVC لتوصيلات المقابس والتمديدات المنزلية العامة.",
    "roll", 38000, 52000, 40, 8, "LOCAL", "Sudan", { Conductor: "Copper", "Cross-section": "2.5 mm²", Length: "100 m" }),
  P("CBL-CU-3X4-50", "Power Cables", "Power Cable 3×4 mm² — 50 m Roll", "كابل كهرباء 3×4 مم² — لفة 50 م",
    "Three-core sheathed copper cable for air conditioners, pumps and sub-panels.",
    "كابل نحاس ثلاثي القلب مغلف للمكيفات والطلمبات واللوحات الفرعية.",
    "roll", 65000, 89000, 15, 3, "IMPORTED", "Egypt", { Cores: "3", "Cross-section": "4 mm²", Length: "50 m" }),
  P("CBL-CAT6-305", "Network & Coaxial Cables", "Cat6 UTP Network Cable — 305 m Box", "كابل شبكة Cat6 UTP — كرتونة 305 م",
    "Cat6 UTP cable for gigabit networks, solid copper conductors in a pull-box.",
    "كابل Cat6 UTP لشبكات الجيجابت بموصلات نحاس مصمتة في كرتونة سهلة السحب.",
    "box", 42000, 60000, 20, 4, "IMPORTED", "China", { Category: "Cat6", Shielding: "UTP", Length: "305 m" }),
  P("CBL-RG6-100", "Network & Coaxial Cables", "RG6 Coaxial Cable — 100 m Roll", "كابل كواكسيال RG6 — لفة 100 م",
    "RG6 coaxial cable for satellite dishes and CCTV with low signal loss.",
    "كابل كواكسيال RG6 للأطباق الفضائية وكاميرات المراقبة بفقد إشارة منخفض.",
    "roll", 18000, 27000, 25, 5, "IMPORTED", "China", { Type: "RG6", Impedance: "75 Ω", Length: "100 m" }),
  P("SW-1G-1W", "Wall Switches", "1-Gang 1-Way Wall Switch", "مفتاح حائط مفرد اتجاه واحد",
    "Classic white 1-gang switch rated 10A with a smooth, durable rocker.",
    "مفتاح حائط مفرد أبيض كلاسيكي بقدرة 10 أمبير ومفتاح ناعم ومتين.",
    "pcs", 900, 1500, 400, 50, "IMPORTED", "Turkey", { Rating: "10 A", Gangs: "1", Colour: "White" }),
  P("SW-TOUCH-3G", "Wall Switches", "Smart Touch Switch 3-Gang Wi-Fi", "مفتاح لمس ذكي 3 خطوط واي فاي",
    "Tempered-glass touch switch with three gangs, app control and timers.",
    "مفتاح لمس بزجاج مقوى بثلاثة خطوط مع تحكم من التطبيق ومؤقتات.",
    "pcs", 7500, 12000, 40, 8, "IMPORTED", "China", { Gangs: "3", Control: "Touch + Wi-Fi app", Panel: "Tempered glass" }),
  P("SK-13A-TWIN", "Sockets & Extensions", "13A Twin Wall Socket (UK Type)", "مقبس حائط مزدوج 13 أمبير (نوع بريطاني)",
    "Switched twin socket, UK three-pin type, rated 13A.",
    "مقبس مزدوج بمفاتيح، نوع بريطاني بثلاثة أطراف، بقدرة 13 أمبير.",
    "pcs", 1400, 2300, 300, 40, "IMPORTED", "Turkey", { Rating: "13 A", Type: "UK 3-pin", Outlets: "2" }),
  P("EXT-4W-3M", "Sockets & Extensions", "4-Way Extension Lead 3 m with Surge Protection", "توصيلة 4 مخارج 3 م مع حماية من الارتفاع المفاجئ",
    "Four-outlet extension lead with surge protection and an illuminated master switch.",
    "توصيلة بأربعة مخارج مع حماية من ارتفاع الجهد ومفتاح رئيسي مضيء.",
    "pcs", 4200, 6800, 70, 10, "IMPORTED", "China", { Outlets: "4", Length: "3 m", Protection: "Surge" }),
  P("CB-MCB-32A", "Circuit Breakers", "MCB Circuit Breaker 32A 1-Pole", "قاطع MCB ‏32 أمبير قطب واحد",
    "Miniature circuit breaker, C-curve, for protecting lighting and socket circuits.",
    "قاطع دائرة مصغر منحنى C لحماية دوائر الإنارة والمقابس.",
    "pcs", 1800, 2900, 200, 30, "IMPORTED", "China", { Rating: "32 A", Poles: "1", Curve: "C", "Breaking capacity": "6 kA" }),
  P("CB-RCD-40A", "Circuit Breakers", "RCD Earth Leakage Breaker 40A 30mA", "قاطع تسرب أرضي RCD ‏40 أمبير 30 مللي",
    "Residual-current device that cuts power on earth leakage to protect people from shock.",
    "جهاز تيار متبقٍ يفصل الكهرباء عند التسرب الأرضي لحماية الأشخاص من الصعق.",
    "pcs", 7000, 11000, 35, 6, "IMPORTED", "China", { Rating: "40 A", Sensitivity: "30 mA", Poles: "2" }),
  P("DB-12W-SURF", "Distribution Boards", "Distribution Board 12-Way Surface Mount", "لوحة توزيع 12 خط تركيب خارجي",
    "Surface-mount consumer unit with DIN rail, neutral and earth bars for 12 modules.",
    "لوحة توزيع للتركيب الخارجي مع قضيب DIN وقضبان للنيوترال والأرضي لـ12 وحدة.",
    "pcs", 9500, 15000, 20, 4, "IMPORTED", "Turkey", { Ways: "12", Mounting: "Surface", Rail: "DIN 35 mm" }),
  P("DB-BUSBAR-1P12", "Distribution Boards", "Pin-Type Busbar 1-Pole 12-Way", "قضيب توصيل (باسبار) قطب واحد 12 خط",
    "Copper pin busbar for fast, tidy linking of single-pole breakers.",
    "باسبار نحاسي بأطراف دبوسية لتوصيل القواطع أحادية القطب بسرعة وترتيب.",
    "pcs", 1500, 2500, 60, 10, "IMPORTED", "China", { Poles: "1", Ways: "12", Material: "Copper" }),
  P("SOL-PNL-550W", "Solar Energy", "Monocrystalline Solar Panel 550W", "لوح طاقة شمسية أحادي البلورة 550 واط",
    "High-efficiency 550W mono PERC panel for home and farm solar systems.",
    "لوح أحادي البلورة PERC عالي الكفاءة بقدرة 550 واط لأنظمة المنازل والمزارع.",
    "pcs", 95000, 135000, 18, 4, "IMPORTED", "China", { Power: "550 W", Type: "Mono PERC", Efficiency: "21%" }),
  P("SOL-MPPT-60A", "Solar Energy", "MPPT Solar Charge Controller 60A", "منظم شحن شمسي MPPT ‏60 أمبير",
    "MPPT charge controller for 12/24/48V battery banks with an LCD display.",
    "منظم شحن MPPT لبطاريات 12/24/48 فولت مع شاشة LCD.",
    "pcs", 48000, 72000, 12, 3, "IMPORTED", "China", { Current: "60 A", "Battery voltage": "12/24/48 V", Display: "LCD" }),
  P("INV-PSW-3KW", "Inverters & UPS", "Pure Sine Wave Inverter 3 kW 24 V", "انفرتر موجة جيبية نقية 3 كيلوواط 24 فولت",
    "3 kW pure sine wave inverter that safely runs fridges, pumps and electronics.",
    "انفرتر موجة جيبية نقية 3 كيلوواط يشغّل الثلاجات والطلمبات والأجهزة الإلكترونية بأمان.",
    "pcs", 180000, 255000, 8, 2, "IMPORTED", "China", { Power: "3 kW", Input: "24 V DC", Waveform: "Pure sine" }),
  P("UPS-1KVA-LI", "Inverters & UPS", "Line-Interactive UPS 1 kVA", "جهاز UPS ‏1 كيلو فولت أمبير",
    "1 kVA UPS with automatic voltage regulation to keep computers running through outages.",
    "جهاز UPS بقدرة 1 كيلو فولت أمبير مع منظم جهد تلقائي لإبقاء الحواسيب تعمل أثناء الانقطاع.",
    "pcs", 52000, 76000, 14, 3, "IMPORTED", "China", { Capacity: "1 kVA", Topology: "Line-interactive", Outlets: "4" }),
  P("TL-MM-AUTO", "Meters & Testers", "Digital Multimeter Auto-Range", "ملتيميتر رقمي تلقائي المدى",
    "Auto-ranging multimeter for voltage, current, resistance and continuity.",
    "ملتيميتر تلقائي المدى لقياس الجهد والتيار والمقاومة والاستمرارية.",
    "pcs", 9000, 14500, 30, 5, "IMPORTED", "China", { Functions: "V, A, Ω, continuity", Safety: "CAT III 600 V" }),
  P("TL-VT-PEN", "Meters & Testers", "Non-Contact Voltage Tester Pen", "قلم فحص الجهد بدون تلامس",
    "Pocket tester that beeps and lights near live wires, 12–1000V AC.",
    "قلم فحص جيبي يصدر صوتًا وضوءًا قرب الأسلاك الحية، من 12 إلى 1000 فولت.",
    "pcs", 2500, 4200, 90, 15, "IMPORTED", "China", { Range: "12–1000 V AC", Alert: "Sound + light" }),
  P("TL-PLR-SET3", "Hand Tools", "Insulated Pliers Set 3 pcs (1000 V)", "طقم زراديات معزولة 3 قطع (1000 فولت)",
    "Combination, long-nose and cutting pliers insulated to 1000V for live work.",
    "زرادية مشتركة وزرادية بوز طويل وقصافة، معزولة حتى 1000 فولت للعمل الآمن.",
    "set", 8500, 13500, 25, 5, "IMPORTED", "China", { Pieces: "3", Insulation: "1000 V VDE" }),
  P("TL-CRIMP-120", "Hand Tools", "Cable Lug Crimping Tool 10–120 mm²", "مكبس كوس كابلات 10–120 مم²",
    "Hexagonal crimping tool for copper lugs from 10 to 120 mm².",
    "مكبس سداسي لتركيب الكوس النحاسية من 10 إلى 120 مم².",
    "pcs", 15000, 23000, 10, 2, "IMPORTED", "China", { Range: "10–120 mm²", Die: "Hexagonal" }),
];

export const SHIPPING_ZONES = [
  {
    zoneName: "Khartoum State",
    governorates: ["Khartoum - Center", "Khartoum - East", "Khartoum - South", "Omdurman - Center", "Omdurman - North", "Bahri - Center", "Bahri - East", "Sharg Al-Neel"],
    shippingCost: 2000,
    deliveryDaysEstimate: "1-2",
  },
  { zoneName: "River Nile & Red Sea", governorates: ["Atbara", "Port Sudan"], shippingCost: 6000, deliveryDaysEstimate: "3-5" },
  { zoneName: "Gezira & Other States", governorates: ["Wad Madani", "Other States"], shippingCost: 6500, deliveryDaysEstimate: "3-7" },
];
