import Cursor from "pg-cursor";
import { Pool } from "pg";
import { NextResponse } from "next/server";
import { auth } from "@/auth";
import { prisma as db } from "@/lib/prisma";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";
export const maxDuration = 300;

const encoder = new TextEncoder();
const globalForBackupPool = globalThis;
const backupPool =
  globalForBackupPool.backupPoolV1 ??
  new Pool({
    connectionString: process.env.DATABASE_URL,
    max: Number(process.env.BACKUP_POOL_MAX || 2),
    idleTimeoutMillis: 10000,
    connectionTimeoutMillis: Number(process.env.DB_CONNECT_TIMEOUT_MS || 15000),
  });

if (process.env.NODE_ENV !== "production") {
  globalForBackupPool.backupPoolV1 = backupPool;
}

function quoteIdent(identifier) {
  return `"${String(identifier).replace(/"/g, "\"\"")}"`;
}

function safeJsonStringify(value) {
  return JSON.stringify(value, (_key, v) => {
    if (typeof v === "bigint") return v.toString();
    return v;
  });
}

function sqlStringLiteral(value) {
  return `'${String(value).replace(/'/g, "''")}'`;
}

function backupFilename(format) {
  const stamp = new Date().toISOString().replace(/[:.]/g, "-").slice(0, 19);
  return format === "sql" ? `db-backup-${stamp}.sql` : `db-backup-${stamp}.json`;
}

function parseBackupFormat(req) {
  const { searchParams } = new URL(req.url);
  const requested = (searchParams.get("format") || "").toLowerCase();
  if (requested === "sql") return "sql";
  return "json";
}

async function writeChunk(writer, text) {
  await writer.write(encoder.encode(text));
}

function readCursor(cursor, size = 200) {
  return new Promise((resolve, reject) => {
    cursor.read(size, (err, rows) => {
      if (err) reject(err);
      else resolve(rows || []);
    });
  });
}

function closeCursor(cursor) {
  return new Promise((resolve) => {
    cursor.close(() => resolve());
  });
}

async function getPublicTables(client) {
  const result = await client.query(`
    SELECT tablename
    FROM pg_catalog.pg_tables
    WHERE schemaname = 'public'
      AND tablename NOT IN ('_prisma_migrations')
    ORDER BY tablename ASC
  `);
  return result.rows.map((r) => r.tablename).filter(Boolean);
}

async function streamJsonBackup(client, writer, tableNames) {
  const meta = {
    format: "json-stream",
    generatedAt: new Date().toISOString(),
    tableCount: tableNames.length,
    tables: tableNames,
  };

  await writeChunk(writer, `{"meta":${safeJsonStringify(meta)},"data":{`);

  for (let i = 0; i < tableNames.length; i += 1) {
    const tableName = tableNames[i];
    const tableSql = `${quoteIdent("public")}.${quoteIdent(tableName)}`;
    const cursor = client.query(new Cursor(`SELECT * FROM ${tableSql}`));
    let firstRow = true;

    await writeChunk(writer, `${i > 0 ? "," : ""}${safeJsonStringify(tableName)}:[`);
    try {
      while (true) {
        const rows = await readCursor(cursor, 200);
        if (rows.length === 0) break;

        for (const row of rows) {
          await writeChunk(writer, `${firstRow ? "" : ","}${safeJsonStringify(row)}`);
          firstRow = false;
        }
      }
    } finally {
      await closeCursor(cursor);
    }
    await writeChunk(writer, "]");
  }

  await writeChunk(writer, "}}");
}

async function streamSqlBackup(client, writer, tableNames) {
  await writeChunk(
    writer,
    `-- SQL backup generated by app\n-- ${new Date().toISOString()}\nBEGIN;\nSET statement_timeout = 0;\nSET lock_timeout = 0;\n`
  );

  for (const tableName of tableNames) {
    const tableSql = `${quoteIdent("public")}.${quoteIdent(tableName)}`;
    await writeChunk(writer, `TRUNCATE TABLE ${tableSql} RESTART IDENTITY CASCADE;\n`);
  }

  for (const tableName of tableNames) {
    const tableSql = `${quoteIdent("public")}.${quoteIdent(tableName)}`;
    const cursor = client.query(new Cursor(`SELECT * FROM ${tableSql}`));

    try {
      while (true) {
        const rows = await readCursor(cursor, 100);
        if (rows.length === 0) break;

        const jsonBatch = safeJsonStringify(rows);
        await writeChunk(
          writer,
          `INSERT INTO ${tableSql} SELECT * FROM json_populate_recordset(NULL::${tableSql}, ${sqlStringLiteral(jsonBatch)}::json);\n`
        );
      }
    } finally {
      await closeCursor(cursor);
    }
  }

  await writeChunk(writer, "COMMIT;\n");
}

async function streamBackup({ format, writer }) {
  const client = await backupPool.connect();
  try {
    const tableNames = await getPublicTables(client);
    if (format === "sql") {
      await streamSqlBackup(client, writer, tableNames);
    } else {
      await streamJsonBackup(client, writer, tableNames);
    }
  } finally {
    client.release();
  }
}

function contentTypeFor(format) {
  return format === "sql"
    ? "application/sql; charset=utf-8"
    : "application/json; charset=utf-8";
}

async function recordBackupSuccess(format) {
  try {
    const store = await db.store.findFirst({
      orderBy: { createdAt: "asc" },
      select: { id: true },
    });
    if (!store) return;
    await db.store.update({
      where: { id: store.id },
      data: {
        backupLastAt: new Date(),
        backupLastStatus: `OK_${String(format).toUpperCase()}_DOWNLOAD`,
      },
    });
  } catch (error) {
    console.error("recordBackupSuccess /api/backup:", error);
  }
}

export async function GET(req) {
  try {
    const session = await auth();
    if (!session?.user?.id || session.user.role !== "ADMIN") {
      return NextResponse.json({ ok: false, error: "unauthorized" }, { status: 401 });
    }

    if (!process.env.DATABASE_URL || !String(process.env.DATABASE_URL).trim()) {
      return NextResponse.json(
        { ok: false, error: "missing_database_url", message: "DATABASE_URL is not configured." },
        { status: 500 }
      );
    }

    const format = parseBackupFormat(req);
    const filename = backupFilename(format);
    const { readable, writable } = new TransformStream();
    const writer = writable.getWriter();

    (async () => {
      try {
        await streamBackup({ format, writer });
        await recordBackupSuccess(format);
        await writer.close();
      } catch (error) {
        console.error("GET /api/backup streaming failed:", error);
        await writer.abort(error);
      }
    })();

    return new Response(readable, {
      status: 200,
      headers: {
        "Content-Type": contentTypeFor(format),
        "Content-Disposition": `attachment; filename="${filename}"`,
        "Cache-Control": "no-store",
        "X-Robots-Tag": "noindex",
      },
    });
  } catch (error) {
    console.error("GET /api/backup:", error);
    return NextResponse.json(
      { ok: false, error: "server", message: error instanceof Error ? error.message : "Backup failed" },
      { status: 500 }
    );
  }
}
